### PR TITLE
Add migrations/`collectstatic` to deployment

### PR DESCRIPTION
**Pull request by justin-sleep**
Similarly to #77, this runs the database migrations and static file collection on container startup, but on staging and production rather than during local development. This was previously a manual process, and I noticed we had missing static assets (icons) after recent staging deployments.

Tested on staging via a manual [workflow run](https://github.com/caim-org/caim-app/actions/runs/6162665448).

Before:
image

After:

### CODE REVIEW

**Comment by rgasper** [comment]
So I'm fairly certain this would make it impossible to reliably rollback a database migration. Because on startup, it'll automatically migrate all applications to the most recent state. You could manually run `python manage.py migrate caim_base ##` after each deploy to maintain the rolled-back state, but that's a pain.

For that reason I'd recommend not including `python manage.py migrate` in the entrypoint, tho I'll say I'm willing to try it out. We may not run into this problem, and then this fix would be a bit nice. And it's not too hard to solve - just stop deploying for a minute, edit the entrypoint, then deploy again. Plus the manual command I described.

I don't think there's any likely issues w/ `collectstatic` running on startup, other than a slowdown to the app launch time

**Review by BenjaminMalley — COMMENTED** [review]
Minor: we can remove deploy.sh in a separate PR. If we need to revert that change for whatever weird reason, we can revert it cleanly. Otherwise LGTM.

**Comment by BenjaminMalley** [comment]
@rgasper wrt to migrations what is the behavior today?

**Comment by justin-sleep** [comment]
> So I'm fairly certain this would make it impossible to rollback a database migration. Because on startup, it'll automatically migrate all applications to the most recent state. For that reason I'd recommend not including python manage.py migrate in the entrypoint.

The typical flow I've seen for permanently reverting database migrations is to undo the model changes, then generate new migrations. I'd push for us not rolling back migrations manually on staging/prod, as if the migrations don't reflect the current state of the database, we lose the value of storing them in version control. Open to pushback!

> Minor: we can remove deploy.sh in a separate PR. If we need to revert that change for whatever weird reason, we can revert it cleanly. Otherwise LGTM.

Since this change is made in its own commit, we'd be able to revert it cleanly without needing a separate PR (e.g. `git revert 138dddb`).

**Comment by BenjaminMalley** [comment]
the concept of rolling back in the context is not super clear to me. iiuc, we can't just rollback to a previous commit and redeploy because we would need to include the migrations to be rolled back. so the best we could do is `manage.py migrate {{rollback_point}}`, which means rolling forward. is that accurate?

**Comment by justin-sleep** [comment]
To flesh out my earlier thoughts:

The primary value that database migrations provide is in allowing us to align our database schema with the application code at any given point in the development history. Along those lines, the migrations included with the latest code should be aligned with the schema the application is expecting at that point in time. If we're ever manually rolling the database back to an earlier migration on staging / prod while leaving the code at the latest commit, it's an antipattern similar to tweaking the application code directly on the server.

> iiuc, we can't just rollback to a previous commit and redeploy because we would need to include the migrations to be rolled back. so the best we could do is manage.py migrate {{rollback_point}}, which means rolling forward. is that accurate?

That's correct. If we need to revert a change that included database migrations that already ran on staging or prod, the solution I would propose is:
1. Revert the relevant commit, but amend the revert commit to exclude the deletion of the database migration file.
2. Generate new migrations from the application in its reverted state.
3. Deploy the application.

An alternative workflow that requires manual intervention on the staging/prod databases is:
1. Revert the relevant commit.
2. Run `manage.py migrate {{rollback_point}}` against the target deployment database.
3. Deploy the application.

The downside of the latter approach is that if a migration is checked in to `main`, wiping it later can create a messy state for developers who have run that migration against their local database. It's the `git` equivalent of erasing a commit from the history rather than reverting it.

**Comment by rgasper** [comment]
> @rgasper wrt to migrations what is the behavior today?

Current behavior is to execute them manually when required. I think that the way @justin-sleep is recommending we do things sounds reasonable to me.

**Review by rgasper — APPROVED** [review]

**Pull request merged**
